name: load-forecasts
channels:
  - conda-forge
dependencies:
  - plotly
  - holoviews
  - hvplot
  - jupyterlab
  - notebook
  - panel
  - scikit-learn
  - diskcache
  - requests
  - pyarrow
  - openpyxl
  - scikit-learn
  - pylint
  - mypy
  - pytest
  - isort
  - black
  - autoflake
  - cartopy
  - geoviews
  - jupyter-panel-proxy
  - pip
  - pip:
    - git+https://github.com/holoviz/panel.git#egg=panel
